apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: argocd-task-sync-and-wait
spec:
  params:
    - name: flags
      default: --
    - name: argocd-version
      default: v1.7.6
  stepTemplate:
    envFrom:
      - configMapRef:
          name: argocd-env-configmap  # used for server address
      - secretRef:
          name: argocd-env-secret  # used for authentication (username/password or auth token)
  steps:
    - name: argocd-app-sync
      image: argoproj/argocd:$(params.argocd-version)
      # TODO: REMOVE insecure flag when using prod server
      script: |
        argocd login $ARGOCD_SERVER --insecure --grpc-web --username $ARGOCD_USERNAME --password $ARGOCD_PASSWORD
        argocd app sync $ARGOCD_APPLICATION_NAME --prune --grpc-web $(params.flags) --server $ARGOCD_SERVER
        argocd app wait $ARGOCD_APPLICATION_NAME --grpc-web --health $(params.flags) --server $ARGOCD_SERVER
