apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Kustomize will add the namespace and labels to all files being kustomized
namespace: tekton-argocd-example
commonLabels:
  pipeline: tekton
  deploy: argocd

resources:
- resources/pipeline-admin-role.yaml
- resources/triggers-admin-role.yaml
- resources/build-task-cm.yaml
- resources/argocd-task-cm.yaml
- tasks/build-task.yaml
- tasks/argocd-task.yaml
- pipelines/build-deploy-pipeline.yaml
- triggers/trigger-template.yaml
- triggers/trigger-binding.yaml
- triggers/event-listener.yaml
- triggers/certificate.yaml
- triggers/ingress.yaml
